### ISSUE TITLE
TypeError: Cannot read property 'controller' of undefined

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/studentslead#82]
https://sentry.io/friday-institute-for-education/studentslead/issues/264417675/

```
TypeError: Cannot read property 'controller' of undefined
  at None (/app/app.js:84:29)
  at None (angular.js:16383:27)
  at m.$eval (angular.js:17682:28)
  at $eval (angular.js:17495:14)
  at $digest (angular.js:17790:12)
...
(4 additional frame(s) were not displayed)
```

**Comment by mjsamberg** [comment]
Resolved by b21f646
